### ISSUE TITLE
GitHub multiple issue reference is incorrect

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/ContributionGuide#2]
To close multiple issues in 1 Pullrequest, `Fixes #32, #40` does not work. It will close issue 32 and only reference issue 40.

To correctly close all issues, the correct notation is `Fixes #32, fixes #40`.

Some more explanation: http://stackoverflow.com/a/3551299/2761676

P.S. if the issues are referenced in a commit and a branch is rebased, it will regenerate a "this issue is referenced in..." message. Therefore it is better to only include references to issues in the PR description.

**Comment by notwaldorf** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.
