### ISSUE TITLE
Jsbin example import misses quote

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/ContributionGuide#4]
The default jsbin linked in CONTRIBUTING.md https://jsbin.com/cagaye/edit?html,output misses a quote in the `paper-button` href import.

If you then edit this import, the jsbin syntax highlighting will crash and editing the jsbin becomes a lot harder.
## Expected outcome

``` html
<link rel="import" href="paper-button/paper-button.html">
```
## Actual outcome

``` html
<link rel="import" href="paper-button/paper-button.html>
```

**Comment by TimvdLippe** [comment]
Friendly ping. @notwaldorf do you have access to the JSBin to add the missing quote?

**Comment by notwaldorf** [comment]
I don't! I think that's @cdata :)

**Comment by cdata** [comment]
@TimvdLippe @notwaldorf I fixed it!

**Comment by notwaldorf** [comment]
Fixed! 🎉

**Comment by TimvdLippe** [comment]
Wow totally missed this one. Thanks a lot @cdata for fixing! :tada:
